services:
  tts:
    tty: true        # docker run -t
    command: "/bin/bash -c 'source /root/miniconda/bin/activate tortoise && python /app/tortoise/socket_server.py'"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tts
    volumes:
      - type: bind
        source: results
        target: /results
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]